README.md

Prueba de la prueba

---

api/src/models/Books.js
api/src/models/Genres.js
api/src/models/Users.js
api/src/routes/index.js
api/src/routes/routesBookId.js
api/src/routes/routesBooks.js
api/src/routes/routesGenres.js
api/src/utils/createBook.js
api/src/utils/getBookDetail.js
api/src/utils/getBooks.js
api/src/utils/getGenres.js

- Cree los archivos base de los 3 modelos 
- Cree los archivos base para las rutas principales y configuré el index con esas rutas
- Cree los archivos base para las principales utilidades

Config inicial back

---

api/src/models/Books.js

feat(src/models books): add models books

---

api/src/models/Books.js
client/package.json
client/src/components/SearchBar/SearchBar.jsx
client/src/redux/actions.js
client/src/redux/reducer.js

SearchBar creado en subcarpeta con estilos, también hecha su action (ruta provisional) y reducer

Feat(003) search bar

---

api/src/models/Books.js
api/src/models/Users.js

- Eliminé el atributo "genre" del model "Books"
- Modifiqué allowNull de "image" y "description" poniendolo en "false" en el model "Books"
- Agregué todos los atributos al model "Users"

Modificación en model Books y creación model Users

---

api/index.js
api/src/db.js
api/src/models/Users.js
api/src/utils/getBookDetail.js
api/src/utils/getBooks.js
api/src/utils/getGenres.js
client/src/components/Card/Card.jsx
client/src/components/Card/Card.module.css
client/src/components/Cards/Cards.jsx
client/src/components/Cards/Cards.module.css
client/src/index.css
client/src/index.js
client/src/pages/Detail/Detail.jsx
client/src/redux/reducer.js

Probando estilos en card y cards

Feat001 lista completa de productos catálogo

---

api/src/models/Books.js
api/src/routes/routesBookId.js
api/src/utils/putBookVisibility.js

- Añadí property "visible" en modelo de books
- Ruta PUT para cambiar la visibilidad de un book pasandole un id como param

feat(src/routes /utils /models): put visible book

---

client/src/pages/Detail/Detail.jsx
client/src/redux/actions.js
client/src/redux/reducer.js

Arregle un poco el detail y agregue la action de get reviews.

Crea pagina Detail.2

---

client/src/App.js
client/src/components/SearchBar/SearchBar.jsx
client/src/components/SearchBar/SearchBar.module.css
client/src/index.css
client/src/index.js
client/src/pages/Detail/Detail.jsx
client/src/pages/Home.jsx
client/src/pages/Home/Home.jsx
client/src/pages/Home/Home.module.css

- Nuevas rutas en App (React Router v5).
- Estructura general de componente Home (WIP!).
- Mini fix en componente detail.

#005 estructura home

---

client/src/api.js
client/src/components/Card/Card.jsx
client/src/components/Card/Card.module.css
client/src/pages/Detail/Detail.jsx
client/src/pages/Detail/Detail.module.css
client/src/pages/Home/Home.jsx
client/src/redux/actions.js

- Ahora el detalle se muestra correctamente.
- Posibilidad de hacer click sobre una card en home y que redirija al detalle.
- Función de clean-up para el action getDetail.

feat(pages/detail): Detalle conectado con home

---

client/src/styles/Card.module.css
client/src/styles/Cards.module.css
client/src/styles/Detail.module.css
client/src/styles/Form.module.css
client/src/styles/Home.module.css
client/src/styles/NavBar.module.css
client/src/styles/SearchBar.module.css

Agregué carpeta de estilos para el que quiera exportarlo a su componente.

 Feat0001 mockup styles

---

api/src/utils/getBookDetail.js
client/src/components/Card/Card.module.css
client/src/components/Card/CardPrueba.module.css
client/src/components/Cards/Cards.module.css
client/src/components/Cards/CardsPrueba.module.css
client/src/components/SearchBar/SearchBar.module.css
client/src/pages/Detail/Detail.module.css
client/src/pages/Detail/DetailPrueba.module.css
client/src/pages/Home/Home.module.css
client/src/pages/Home/HomePrueba.module.css

feat(css modules): Css archivos nuevos

---

api/src/routes/routesBooks.js
api/src/utils/getBooksByAll.js

-Utils: getBooksByAll
-routesBooks

Utils: getBooksByAll. Agrego a routesBooks el getBooksByAll

---

api/src/models/Users.js
api/src/routes/index.js
api/src/routes/routesUsers.js
api/src/utils/getUser.js
api/src/utils/postUser.js

El setter de la contrasena da error, no termine pero lo voy subiendo, me decia que no se puede meter un array

post y get user

---

client/package.json
client/src/pages/CreateBook/CreateBook.jsx
client/src/pages/CreateBook/CreateBook.module.css

-Uso de libreria sweetalert2
-Mejora en formulario para nombre, autor, editorial y alerts

002 form manejar errores

---

api/src/routes/index.js
api/src/routes/routesCart.js
api/src/utils/getCart.js
client/src/App.js
client/src/components/NavBar/NavBar.jsx

Ruta cart y funcion getCart sin logica
Front pages cart nomas
NavBar el icono carrito redirige a /cart

Back02 ruta carrito

---

api/src/utils/getAllBooks.js
api/src/utils/putBookVisibility.js
client/src/components/Card/Card.jsx
client/src/components/Card/CardPrueba.module.css
client/src/pages/Detail/Detail.jsx
client/src/pages/Detail/DetailPrueba.module.css
client/src/pages/Home/Home.jsx
client/src/redux/actions.js
client/src/redux/reducer.js

- Ocultar productos tanto desde el detalle como desde el home, con respuesta visual inmediata.
- En ambos casos se obtiene una respuesta visual de que el producto esta oculto.
- Mínimos cambios en el back para que la funcionalidad sea más a grata.

Front(004) ocultar productos

---

api/src/db.js
api/src/models/Books.js
api/src/models/Cart.js
api/src/models/Reviews.js
api/src/models/Users.js
api/src/models/Wishlist.js

- Fix modelo Users y Books
- Create modelo Wishlist, Cart, Reviews
- Relaciones entre todos en archivo "db"

Back04 fix modelos

---

api/src/routes/routesBookId.js
api/src/utils/putBook.js

Nueva ruta PUT para modificar los libros, solo back.

feat(/src/utils):Nueva ruta put

---

api/src/routes/index.js
api/src/routes/routesReviews.js
api/src/routes/routesUsers.js
api/src/utils/getBookDetail.js
api/src/utils/postReviews.js
api/src/utils/postUser.js

- Nueva ruta a /reviews para el POST de las reseñas.
- Nuevo archivo postReviews en "/utils".
- Fix en postUser acomodando la info que mandamos.
- Fix en getBookDetail para que además de lo que traía el detalle ahora incluya las reviews.

Reviews en back, fix en postUser, fix en getBookDetail

---

client/src/App.js
client/src/pages/Home/Home.jsx
client/src/pages/ProfileUser/ProfileUser.jsx

cree nuevo archivo profileUser
agregue la ruta a /profile en componente App

Front006 perfil usuario

---

.vscode/settings.json
api/src/routes/routesBookId.js
api/src/utils/putBook.js
client/src/App.js
client/src/components/Card/Card.jsx
client/src/components/Card/CardPrueba.module.css
client/src/pages/CreateBook/CreateBook.jsx
client/src/pages/CreateBook/CreateBook.module.css
client/src/pages/Detail/Detail.jsx
client/src/pages/Home/Home.jsx
client/src/redux/actions.js
client/src/redux/reducer.js

- Creación de toda la lógica en el front para editar un libro en específico, pudiendo acceder tanto desde el home como desde el detalle.
- Adaptación del componente CreateBook para que también pueda usarse para la edición de libros.
- Creación de nueva action en el susodicho archivo y case en el reducer, mínimo feat en back (putBook).
- Correcciones en CSS del form y eliminación de validaciones HTML.

Front(020) admin editar libro

---

api/src/routes/routesBooks.js
api/src/utils/getAllBooks.js
api/src/utils/getBooksByAll.js
api/src/utils/getBooksByAuthor.js
api/src/utils/getBooksByFilters.js
api/src/utils/getGenres.js
api/src/utils/postAllBooks.js
api/src/utils/postAllGenres.js
api/src/utils/postBook.js
api/src/utils/postReviews.js
api/src/utils/putBook.js
api/src/utils/putBookVisibility.js
client/src/components/FiltersNav/FiltersNav.jsx
client/src/components/SearchBar/SearchBar.jsx
client/src/pages/CreateBook/CreateBook.jsx
client/src/pages/Home/Home.jsx
client/src/redux/actions.js
client/src/redux/reducer.js

- SweetAlert para errores de filtros y searchbar, le puse un mini estilo al alert , si no les gusta se cambia o borra
- Borré líneas de código que estaban de más y no se usaban xd

Front003 mjes error filtros search bar

---

client/package.json
client/src/components/NavBar/NavBar.jsx
client/src/firebase/auth.js
client/src/pages/ProfileUser/ProfileUser.jsx
client/src/pages/Register/Register.jsx
client/src/pages/Register/Register.module.css

Estilos - hice algunos estilos pero no me gustaron (en register y profile), si alguno tiene ganas de cambiarlos que lo haga sino lo hago despues.
Validaciones- le faltan un par de validaciones al register y tambien al login

react form, validaciones y estilos

---

api/src/routes/routesCart.js
api/src/utils/getGuestCart.js
api/src/utils/getUserCart.js
api/src/utils/postCart.js

routes, gets guest y user carrito, post carrito

routesCart, getUserCart, getGuestCart, postCart

---

client/src/pages/Cart/Cart.jsx
client/src/pages/Detail/Detail.jsx
client/src/redux/actions.js
client/src/redux/reducer.js

- localStorage ahora guarda hasta un número determinado de productos y de sus existencias.
- Action para postear carrito del user y para traer la información de los libros del mismo.

Front(007) carrito

---

client/src/components/NavBar/NavBar.jsx
client/src/components/Review/Review.jsx
client/src/pages/Cart/Cart.jsx
client/src/pages/Cart/Cart.module.css
client/src/pages/Detail/Detail.jsx
client/src/redux/actions.js

SOLO PARA USUARIO NO INVITADO:
- Terminé de acomodar la lógica de los botones tanto para sumar como restar libros.
- Agregué contadores en el detalle y en el NavBar.
- Hice un poco de estilos en el componente carrito

Front005 carrito mati

---

api/src/routes/routesUsers.js
api/src/utils/putUser.js
client/src/pages/ProfileUser/ProfileUser.jsx
client/src/pages/ProfileUser/ProfileUser.module.css

-Faltan estilos.
-Falta que cuando edites veas los cambios instantaneamente.
-Creo que vamos a tener que sacar user de estado global y lo vamos a tener que pedir donde lo necesitemos o alguna otra cosa

Editar perfil usuario

---

client/src/pages/Detail/Detail.jsx
client/src/pages/Detail/DetailPrueba.module.css

Solo hice que las reviews se promedien así se muestran X estrellas en el detalle del libro. ⭐🌟⭐🌟⭐

Fix rating, ahora promedia con reviews

---

client/src/components/NavBar/NavBar.jsx
client/src/pages/Cart/Cart.jsx
client/src/pages/Detail/Detail.jsx
client/src/pages/Home/Home.jsx

- Fixed carrito en algunos archivos y limpieza de código.

Front005b carrito mati user

---

client/src/components/Error/Error.jsx
client/src/components/Error/Error.module.css
client/src/helpers/useUser.jsx
client/src/pages/ProfileUser/ProfileUser.jsx

-Custom hook para saber si usuario existe
-Componente error para mostrar errores

Fix(06) user no aparece

---

client/src/components/Card/CardPrueba.module.css
client/src/components/FiltersNav/FiltersNav.module.css
client/src/components/Footer/Footer.jsx
client/src/components/Footer/Footer.module.css
client/src/components/NavBar/NavBar.module.css
client/src/pages/Home/HomePrueba.module.css

Fix filters Nav, footer y cards

Fix3 css nav bar

---

client/src/components/Card/CardPrueba.module.css
client/src/components/FiltersNav/FiltersNav.module.css
client/src/components/Footer/Footer.module.css
client/src/components/NavBar/NavBar.module.css
client/src/components/SearchBar/SearchBar.module.css
client/src/pages/Detail/DetailPrueba.module.css

Fix del bugsito del boton user

fix del bug en boton user

---

client/src/components/Review/Review.jsx
client/src/pages/Cart/Cart.jsx
client/src/pages/CreateBook/CreateBook.jsx
client/src/pages/CreateBook/CreateBook.module.css
client/src/pages/Home/Home.jsx
client/src/pages/Login/Login.jsx
client/src/pages/Register/Register.jsx

se modificaron los sweetalert para que sea mas agradable al entorno dark y algo del cambio en el css del formulario

modificacion de los sweetalert y algo del css en formulario

---

client/src/components/Card/CardPrueba.module.css
client/src/components/NavBar/NavBar.jsx
client/src/components/NavBar/NavBar.module.css
client/src/components/Review/Review.jsx
client/src/components/SearchBar/SearchBar.jsx
client/src/pages/Cart/Cart.jsx
client/src/pages/CreateBook/CreateBook.module.css
client/src/pages/Detail/DetailPrueba.module.css

Leves retoques a varios componentes: navbar, searchbar, detail, review y alguno más.

Fix CSS general

---

client/src/pages/Home/Home.jsx

Pequeño fix en home

---

client/src/components/NavBar/NavBar.module.css
client/src/pages/Home/Home.jsx
client/src/pages/Home/HomePrueba.module.css

Desactivé botones anterior y siguiente de paginado cuando la página es igual a 1 y cuando es la última.
Fix de un bug en el nav.

Desactivar botones anterior y siguiente de paginado y fix bug en navBar

---

api/src/utils/pagination.js
client/src/components/Card/CardPrueba.module.css
client/src/pages/Home/Home.jsx
client/src/pages/Home/HomePrueba.module.css

Fix de las cards en home con flexbox, modifiqué el paginado para traiga 12 en vez de 10 para no romper la caja si la pantalla es más chica.
Fix del css.

Fix004 reestructar cards

---

api/src/routes/routesBookId.js
api/src/utils/getAllBooks.js
api/src/utils/getBooksByFilters.js
api/src/utils/postBook.js
api/src/utils/putBook.js
client/src/pages/CreateBook/CreateBook.jsx
client/src/pages/Detail/Detail.jsx
client/src/redux/actions.js
client/src/redux/reducer.js

- Agregué un useEffect en detail que hace que cada vez que entramos le agrega una visita en la DB.
- Creé action y reducer para nuevos filtrados para landing (más baratos, más puntuados, más visitados).
- Hice modificaciones en back tanto en getAllBooks(Para incluir las reviews), como en getBooksByFilters (para añadir los nuevos filtros).
- Quitamos el capitalize, ahora el dueño puede agregar los títulos de los libros como él quiere.

Fix06 fix visits detail

---

client/src/components/Card/CardPrueba.module.css
client/src/components/FiltersNav/FiltersNav.jsx
client/src/components/FiltersNav/FiltersNav.module.css
client/src/components/NavBar/NavBar.jsx
client/src/components/NavBar/NavBar.module.css
client/src/components/SearchBar/SearchBar.module.css
client/src/pages/Home/HomePrueba.module.css

Fix css filtros, los cambié de lugar abajo de nav.
Fix en navBar

css en filtros y fix en navBar

---

api/src/utils/postBook.js
client/package.json
client/src/firebase/firebase.js
client/src/pages/CreateBook/CreateBook.jsx
client/src/pages/CreateBook/CreateBook.module.css

- Ahora podemos subir una foto en el formulario de editar y crear un libro.
- Estilos aplicados y mini fixes.
- UUIDv4 instalado en el front! (usar: npm i uuid)

Front(03) admin subir fotos

---

client/src/pages/Cart/Cart.jsx

-Cart, borrar un libro y el carrito entero para el guest listo.
-Cart, sweetalert, colores y width adaptados

Front008 eliminar book carrito

---

api/package.json
api/src/nodemailer/index.js
api/src/nodemailer/templates.js
api/src/utils/postUser.js
client/src/helpers/templateAlert.js
client/src/pages/CreateBook/CreateBook.jsx
client/src/pages/CreateBook/CreateBook.module.css
client/src/pages/Register/Register.jsx

- Nodemailer integrado.
- Al registrarnos envía un correo electronico con el gmail de la empresa y nos lo notifica vía una sweetalert.
- Template para alertas en carpeta "helpers", así resumimos código.
- Mini fixes en componente create/edit
Nueva librería en el back!! `npm install nodemailer`

Front(07 08) user nodemailer

---

client/src/pages/Cart/Cart.jsx

trash en user

---

client/src/components/Footer/Footer.jsx

link borrado

---

api/src/models/Cart.js
api/src/models/Users.js
api/src/routes/routesUsers.js
api/src/utils/getAllUsers.js
api/src/utils/putUser.js
client/src/components/PanelOrders/PanelOrders.jsx
client/src/components/PanelUsers/PanelUsers.module.css

Modificacion en model Users y Carts. Algunos fixes

Modificaciones en models.

---

api/src/routes/routesUsers.js
api/src/utils/getAllUsers.js
api/src/utils/postAllGenres.js
api/src/utils/postCheckout.js
client/src/components/PanelUsers/PanelUsers.jsx
client/src/components/PanelUsers/PanelUsers.module.css
client/src/redux/actions.js
client/src/redux/reducer.js

Avances dashboard

---

api/src/routes/routesGenres.js
api/src/utils/getGenres.js
client/src/components/PanelBooks/PanelBooks.jsx
client/src/components/PanelGenres/PanelGenres.jsx
client/src/components/PanelGenres/PanelGenres.module.css
client/src/pages/CreateBook/CreateBook.jsx
client/src/pages/CreateBook/CreateBook.module.css
client/src/pages/Dashboard/Dashboard.jsx
client/src/redux/actions.js
client/src/redux/reducer.js

Formulario de agregar libros acomodado para el panel de admin. Si quieren cambiar algo de los estilos después me avisan y lo cambio

Front012 dashboard admin

---

client/src/components/NavBar/NavBar.jsx
client/src/components/PanelUsers/PanelUsers.module.css
client/src/components/SearchBar/SearchBar.jsx
client/src/components/SearchBar/SearchBar.module.css
client/src/components/SearchBar/prueba.css
client/src/pages/CreateBook/CreateBook.module.css
client/src/redux/reducer.js

- Fix errores del carrito.
- Acomodamos el css del searchbar que no estaba centrada en altura y además juntamos todo en un mismo lugar porque había dos css distintos.

Fix error del carro, acomodamos css de searchbar

---

api/src/utils/getUserCart.js
api/src/utils/pagination.js
client/src/pages/UserProfile/UserProfile.jsx

-Ruta getUserCart por ahora para detectar que no quiero los carritos de status abierto, puse que si incluye un - busque los de status entregado y procesando. Si se les ocurre alguna otra idea lo cambio.
-Se ve las compras en perfil.(Por ahora lo puse abajo de los datos del perfil)
-Boton ver mas

mis compras

---

client/src/pages/Stripe/Stripe.jsx
client/src/pages/Stripe/Stripe.module.css

Estilos no terminados del checkout x3

---

client/src/pages/Cart/Cart.jsx
client/src/pages/Cart/Cart.module.css
client/src/redux/reducer.js

Lo que dice el commit y fix de reducer get_cart

Estilos basicos al boton

---

client/src/components/NavBar/NavBar.jsx
client/src/components/NavBar/NavBar.module.css
client/src/components/Review/Review.jsx
client/src/pages/Cart/Cart.jsx
client/src/pages/Detail/Detail.jsx
client/src/pages/Login/Login.jsx

-Admin puede eliminar reseñas desde el detail.
-User baneado puede ver las reseñas.
-Diferencia de admin en login, si se logea como admin no trae las cosas del carrito de invitado.
-Botón iniciar sesión si se está como invitado.
-Arreglé lo del vaciar carrito en el user, llegaba con delay.

Front04 diferencia admin user

---

client/src/index.css
client/src/pages/Stripe/Stripe.jsx
client/src/pages/Stripe/Stripe.module.css

estilos stripe

---

client/src/components/Footer/Footer.jsx
client/src/components/Footer/Footer.module.css
client/src/index.css
client/src/pages/Detail/Detail.jsx
client/src/pages/Detail/DetailPrueba.module.css
client/src/pages/Home/HomePrueba.module.css
client/src/pages/Stripe/Stripe.jsx
client/src/pages/Stripe/Stripe.module.css

-Faltan algunos estilos.
-Estilos footer arreglado.
-En carrito todavia genera problemas. Si hay problemas en otro lado avisen.

Front06 stripe

---

client/src/components/Review/Review.module.css

fix review css

---

api/src/utils/getGuestCart.js
api/src/utils/getUserCart.js
client/src/pages/Cart/Cart.jsx
client/src/pages/Detail/Detail.jsx
client/src/pages/LandingPage/LandingPage.jsx
client/src/pages/Login/Login.jsx
client/src/pages/UserProfile/UserProfile.jsx
client/src/redux/reducer.js

gestionar stock en detail, correcciones

Front09 gestionar stock

---

client/src/App.js
client/src/firebase/auth.js
client/src/firebase/firebase.js
client/src/pages/Detail/Detail.jsx
client/src/pages/Stripe/Stripe.jsx
client/src/pages/UserProfile/UserProfile.jsx
client/src/redux/actions.js

Fix del maximo de carrito 
elimine los localhost del front

Merge main

---

client/src/components/Footer/Footer.jsx
client/src/components/NavBar/NavBar.jsx
client/src/pages/UserProfile/UserProfile.jsx
client/src/pages/UserProfile/UserProfile.module.css

Estilos perfil e historial de compras terminados
Fix error en navBar en perfil
Fix botón regresar -ahora redirige a Home-

Css002 perfil

---

api/config.js
api/src/nodemailer/templateDelivered.js
api/src/nodemailer/templatePurchase.js
api/src/nodemailer/templateWelcome.js
api/src/nodemailer/templates.js
api/src/routes/routesCart.js
api/src/utils/postCheckout.js
api/src/utils/postUser.js
api/src/utils/putCartStatus.js
client/src/components/PanelOrders/PanelOrders.jsx
client/src/pages/Register/Register.jsx
client/src/pages/Stripe/Stripe.jsx
client/src/pages/UserProfile/UserProfile.jsx
client/src/redux/actions.js

-Mails con estilos y en todas las posibilidades

Front nodemailer

---

client/src/App.js
client/src/components/NavBar/NavBar.jsx
client/src/components/NavBar/NavBar.module.css
client/src/pages/LandingPage/LandingPage.jsx
client/src/pages/LandingPage/LandingPage.module.css
client/src/pages/Login/Login.jsx
client/src/pages/UserProfile/UserProfile.jsx

x2 arreglo de rutas landing y home, implemento icono de casa, y otros detalles

Fixes landing

---

api/config.js
client/src/components/NavBar/NavBar.module.css
client/src/components/SearchBar/SearchBar.jsx
client/src/pages/Cart/Cart.jsx
client/src/pages/LandingPage/LandingPage.jsx

puse un link que lleva a populares cuando el carrito vacio
arreglo de searchbar cambiando la ruta

Fix04 agregar opciones detail carro

---

api/src/utils/getAllBooksAdmin.js
api/src/utils/getAllUsers.js
api/src/utils/getOrders.js
api/src/utils/postBook.js
client/src/pages/CreateBook/CreateBook.jsx
client/src/pages/CreateBook/CreateBook.module.css
client/src/pages/Stripe/Stripe.jsx

- Mejores validaciones en el form.
- Mini fixes en search del dashboard

Fix(015) validaciones form mejoradas

---

client/src/components/Card/CardPrueba.module.css
client/src/components/Review/Review.module.css
client/src/pages/Cart/Cart.module.css
client/src/pages/CreateBook/CreateBook.module.css
client/src/pages/Dashboard/Dashboard.module.css
client/src/pages/Home/HomePrueba.module.css

fix opacity deploy

---

client/src/pages/Login/Login.jsx

alerta al ingresar mal contraseña

Fix005 error login

---

client/src/pages/Cart/Cart.jsx
client/src/pages/Detail/DetailPrueba.module.css

Fix009 user estilos detail

---

client/src/components/Footer/Footer.jsx
client/src/components/NavBar/NavBar.jsx
client/src/components/NavBar/NavBar.module.css
client/src/components/PanelUsers/PanelUsers.jsx
client/src/pages/LandingPage/LandingPage.module.css

Fix nav estilos

---

client/src/pages/Cart/Cart.jsx
client/src/pages/Cart/Cart.module.css

Fix estilos carrito
